// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egahpdotgfvajhywxenq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnYWhwZG90Z2Z2YWpoeXd4ZW5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNjc3MzEsImV4cCI6MjA1Njc0MzczMX0.m37zs_lOygmDawCriBzi904JuSCYJlHt3eUuwRUmygU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);